format_version: v1.0
configName: samd21
folderName: samd21
frameworkPath: C:\MCHP\MCC
processor: ATSAMD21G17D
projectName: samd21
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMD21_DFP\3.6.144\samd21d\atdf\ATSAMD21G17D.atdf
